title: 0xMikasa                       # your blog name
tagline: Breaking things, legally.   # your subtitle
description: Security writeups, HTB machines, and notes from the field.
url: "https://mikasa-ack0x.github.io/"

github:
  username: mikasa-ack0x

avatar: /assets/pfp.jpeg       # add a photo later

timezone: Asia/Kolkata
lang: en
